### ISSUE TITLE
Make ezhc work with python 3

### ISSUE THREAD

**Issue by garaud** [oscar6echo/ezhc#3]
Hi,

I'm on it with but I've not finished yet (I use Python3.4)
Take a look at https://github.com/garaud/ezhc/commits/py3-compat

I've got some trouble to display the tree maps with a JS error such as `TypeError: Cannot read property 'push' of undefined`. I'm digging...

**Comment by oscar6echo** [comment]
Ok, since I don't use (yet ?) Python 3.x I'll trust you with the tests.
