### ISSUE TITLE
additing button to html 

### ISSUE THREAD

**Issue by gcmitter** [oscar6echo/ezhc#4]
Is there a way to add buttons to the stand alone HTML via the python script calling the exhc libraries. I am trying to group the data using highstock by unit, year, month, week, day, but not able to. I tried using.
g.exporting.buttons.customButton2={
    'text':"Monhtly",
    'x': -780,
    'onclick': "function () {alert('Clicked');}"
and for the function I tried 'onclick': """function (){series":{"animation":true,"dataGrouping":{"approximation":"sum","forced":true
but can not get it to work, I can see the button but having issue with been able to run the function. 
Please comment. 
This is not an issue just need some support adding some functionality to the html. also did not have any other way to reach, email would help.
Regards,

**Comment by oscar6echo** [comment]
Hi,

Before questioning/debugging ezhc, it is usually good practise to try the javascript code directly and see whether all runs according to plan.

For that I find jsfiddle very convenient. For example you may want to test a simple version of your Highstock code in a fork from http://jsfiddle.net/d86s8yd8/ which I found browsing Highstock api http://api.highcharts.com/highstock#exporting.buttons.contextButton.onclick. There are literally tons of examples available, virtually one per config param, which you can run/modify/rerun.

By the way this is one of the reasons why I chose to wrap this lib in the notebook: Comprehensive API and easy testing/debugging.

If the jsfiddle works but not the ezhc call in the nb then please post both somewhere and I will try to have a look.

Rgds

**Comment by gcmitter** [comment]
Thanks the reply and noted on the comments... I was able to get he button in the py scrip from your examples by adding 
g.exporting.buttons.customButton={    'text':"Daily",    'x': -894,    'onclick': "function () {chart.series[0].update({ dataGrouping: { forced: true, units: [ ['day', [1]] ] }, type: 'column' })}",    }
Now I am trying to create the following long heatmap, but can not begging to get it to work.. I am I would like to be able to do the do the extended heat using your ezhc code, just like the example you put on notebook for sales people, but I can't, would like to just present the df data and build .py sets it up, just liek the exmplae you have for heat map but for extended heat map http://nbviewer.jupyter.org/github/oscar6echo/ezhc/blob/master/demo_ezhc.ipynb. . Is there a way you could get that done, I can can pay you for the work? please let me know. regards. Edit fiddle - JSFiddle

```
On Wednesday, March 2, 2016 2:18 PM, oscar6echo <notifications@github.com> wrote:
```

 Hi,Before questioning/debugging ezhc, it is usually good practise to try the javascript code directly and see whether all runs according to plan.For that I find jsfiddle very convenient. For example you may want to test a simple version of your Highstock code in a fork from http://jsfiddle.net/d86s8yd8/ which I found browsing Highstock api http://api.highcharts.com/highstock#exporting.buttons.contextButton.onclick. There are literally tons of examples available, virtually one per config param, which you can run/modify/rerun.By the way this is one of the reasons why I chose to wrap this lib in the notebook: Comprehensive API and easy testing/debugging.If the jsfiddle works but not the ezhc call in the nb then please post both somewhere and I will try to have a look.Rgds—
