### ISSUE TITLE
Access to setOptions

### ISSUE THREAD

**Issue by jasonwillschiu** [oscar6echo/ezhc#6]
Hi Oscar,

Not sure if it's an issue, but I was wondering if we had access to setOptions via ezhc?

Referring to the API reference (https://api.highcharts.com/highcharts), I have used ezhc with many options via the "Highcharts.chart({" stream, however I haven't got anything to work on the "Highcharts.setOptions({" stream.

Is there a way to access setOptions?

As a simple example I'm trying:
hc.Highcharts().setOptions.lang.thousandsSep = ','

but receiving the error
AttributeError: 'NoneType' object has no attribute 'lang'

Thanks,
Jason

**Comment by oscar6echo** [comment]
Hi Jason,

As you correctly observed, there is currently no access to setOptions via ezhc.   
When I wrote it either setOptions was not there or I did not notice it.  

Note that in ezhc a Highcharts() object does not correspond to the javascript Highcharts object but rather to a Highcharts.Chart object. And once instantiated, you cannot access it any more. There is no bi-directional communication Python-JS. Python is just used to write JS and inject it in the output_area of a code cell. Then the browser simply renders it.  
To have a clearer view of what's going on under the hood it's good to open the browser console and navigate the Highcharts objects available. ezhc is verbose (in the console) and displays the handles (they include long uuid strings to avoid collision among several ezhc objects). 

You are right that setOptions should be accessible from ezhc.  
So I will add a HighchartsGlobal (or similar name) Python class that can be instantiated with global and lang properties to modify their default settings.

I cannot guarantee when yet as quite busy, hopefully this month.  
Thanks for the useful feedback.

**Comment by jasonwillschiu** [comment]
Hi Oscar,

Thanks for the explanation. If you get a chance, that would be great. No rush.

**Comment by oscar6echo** [comment]
Hi Jason,

Checkout version 0.7.   
I updated ezhc to:

- add access to global options
- make available official themes very simply
- beef up the examples with sunburst diagrams and more flexible scatter plots.  


Hope this helps.

Thx

**Comment by jasonwillschiu** [comment]
Hi Oscar,

I have updated my notebook to use global options and it works great!
Thank you very much for your work on updating and documenting ezhc.

Another thing, I'm wondering if there is a way to suppress the output from global options and themes?
I've tried ending lines with ';' but that didn't work, so for now I use the %%capture magic.

If there's no easy way to do this then that's no problem either!

Cheers,
Jason

**Comment by oscar6echo** [comment]
Jason,

To accommodate your need I just published version 0.7.1.  
Now to suppress the output of `GlobalOptions.inject()` just set `verbose=False`.  
See the [demo notebook](http://nbviewer.jupyter.org/github/oscar6echo/ezhc/blob/master/demo_ezhc_themes_and_global_options.ipynb).

Hope this helps,  
Thx

**Comment by jasonwillschiu** [comment]
Hi Oscar, 

That's perfect. Thank you!

Let me know if I can help you in some way one day!

Jason
